# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import QMenu , QMainWindow ,QMessageBox
import os

from editphongtro import Gui_2 
paths = [
    "C:\\",
    "Users",
    os.getlogin(),
    "Desktop",
    "python",
    "app"
]
for pathh in paths:
    os.chdir(pathh)

def read_txt():
    with open("value.txt","r") as files:
        line = files.read()
        numbers = ''.join(filter(str.isdigit,line))
        number = int(numbers)
        return number

def remove_text_from_file(file_name, text_to_remove):
    
        # Mở tệp văn bản để đọc
        with open(file_name, 'r') as file:
            lines = file.readlines()

        
        # Xóa chuỗi xác định khỏi nội dung
        updated_lines = [line.replace("Phong_tro:"+str(text_to_remove), '') for line in lines]

        # Mở tệp văn bản ở chế độ ghi
        with open(file_name, 'w') as file:
            file.writelines(updated_lines)


class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(944, 610)
        MainWindow.setMaximumSize(QtCore.QSize(944, 610))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.danhsachphongtro = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.danhsachphongtro.setMaximumSize(QtCore.QSize(551, 101))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.danhsachphongtro.setFont(font)
        self.danhsachphongtro.setObjectName("danhsachphongtro")
        self.gridLayout.addWidget(self.danhsachphongtro, 0, 0, 1, 1)
        self.Themphongtro = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Themphongtro.setMaximumSize(QtCore.QSize(321, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Themphongtro.setFont(font)
        self.Themphongtro.setObjectName("Themphongtro")
        self.gridLayout.addWidget(self.Themphongtro, 0, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setMaximumSize(QtCore.QSize(911, 411))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 892, 409))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)

        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        # them code
        self.value = read_txt()
        self.danhsachphongtros = [] #các số nhà trọ
        self.danhsachphongtro_value = [] # các button
        self.name = None
            #menu chuột phải
        self.context_menu = QMenu()
        self.delete = self.context_menu.addAction("Delete")
        self.edit = self.context_menu.addAction("Edit")
        self.delete.triggered.connect(self.delete_func)
        self.edit.triggered.connect(self.edit_func)
       
        #
        self.retranslateUi(MainWindow)
        self.show_phongtro()
        self.show_buttonphongtro()
        
        # for i in self.danhsachphongtros:
        #     print(i)
        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    


    def show_phongtro(self):
        with open(f"nhà {self.value}.txt","r") as file :
             lines = file.readlines()
        
        for line in lines :
            line = line.replace("\n", "")
            parts = line.split(":")
            if len(parts) == 2 and parts[0].strip() == "Phong_tro":  
                self.danhsachphongtros.append(parts[1])
        
    def show_buttonphongtro(self) :
        if self.danhsachphongtros != []:
            self.len_danhsachphongtros = len(self.danhsachphongtros)
            font = QtGui.QFont()
            font.setPointSize(16)
            
            for i in range(self.len_danhsachphongtros):
                
                self.name_phongtro = QtWidgets.QPushButton("Phòng "+self.danhsachphongtros[i],parent=self.scrollAreaWidgetContents_2)
                self.name_phongtro.setFont(font)
                self.name_phongtro.setObjectName(f"pushButtonphong_{self.danhsachphongtros[i]}")
                self.danhsachphongtro_value.append(self.name_phongtro)
                
            for i in self.danhsachphongtro_value: 
                self.verticalLayout.addWidget(i)
            for button, name in zip(self.danhsachphongtro_value, self.danhsachphongtros):
                button.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
                button.customContextMenuRequested.connect(lambda pos, name=name: self.show_context_menu(name))
            
    def show_context_menu(self,name):        
        cursor = QtGui.QCursor()
        global_pos = cursor.pos()
        self.name = name
        print(self.name)
        self.context_menu.exec(global_pos)
    
        
        
    def delete_func(self):
        remove_text_from_file(f"nhà {self.value}.txt",self.name)
        delete_phongtro = "Phòng " + self.name 
        for i in self.danhsachphongtro_value :
            if i.text() == delete_phongtro:
                i.deleteLater()
                self.danhsachphongtro_value.remove(i)
        for i in self.danhsachphongtros:
            if i == self.name:
                self.danhsachphongtros.remove(i)
        if os.path.exists(f"phòng {self.name}.txt"):
                os.remove(f"phòng {self.name}.txt")
    def edit_func(self):
        
        self.win_add = QMainWindow()
        self.uic_add = Gui_2()

        self.uic_add.setupUi(self.win_add)
        self.win_add.show()
        self.uic_add.pushButton.clicked.connect(self.buttonok_in_buttonedit)
    def buttonok_in_buttonedit(self):
        text = self.uic_add.plainTextEdit.toPlainText()
        if text == "":
            message_box = QMessageBox()
            message_box.setIcon(QMessageBox.Icon.Information)  # Đặt biểu tượng (Information, Warning, Critical, NoIcon, vv.)
            message_box.setText("Không phù hợp")  # Đặt nội dung thông báo
            message_box.setWindowTitle("Thông Báo")  # Đặt tiêu đề của message box

            # Thêm nút hoặc lựa chọn vào message box (ví dụ: nút OK)
            message_box.addButton("OK", QMessageBox.ButtonRole.AcceptRole)

            # Hiển thị message box và đợi người dùng tương tác
            result = message_box.exec()
        else:        
        # Mở file text ,tìm số phòng trọ cần sửa , 
            with open(f"nhà {self.value}.txt", 'r') as file:
                lines = file.readlines()
            new_lines = []
            for line in lines:
                if line.strip().startswith("Phong_tro:"):
                    new_line = f"Phong_tro:{text}\n"  
                    new_lines.append(new_line)
                else:
                    new_lines.append(line)
            with open(f"nhà {self.value}.txt", 'w') as file:
                file.writelines(new_lines)
        # replace phần tử trong self.danhsachphongtros
            for i in range(self.len_danhsachphongtros):
                if self.danhsachphongtros[i] == self.name :
                    self.danhsachphongtros[i] = text
                    
        # đổi tên phần tử trong self.danhsachphongtro_value = text , object name = text 
            for i in self.danhsachphongtro_value:
                numbers_phongtro = ''.join(filter(str.isdigit,i.text()))
                if numbers_phongtro == self.name:
                    i.setText("Phòng "+text)
                    i.setObjectName("pushButtonphong_"+text)
        # đổi tên file text phòng trọ 
            if os.path.exists(f"phòng {self.name}.txt"):
                os.rename(f"phòng {self.name}.txt",f"phòng {text}.txt")
            
            self.name = None
            
             
            self.win_add.close()

        
    def add_buttonphongtro(self,text):
            font = QtGui.QFont()
            font.setPointSize(16)
            if text != "" :
                namephongtro =  QtWidgets.QPushButton("Phòng "+ text,parent=self.scrollAreaWidgetContents_2)  
                namephongtro.setFont(font)
                namephongtro.setObjectName(f"pushButtonphong_{text}")
                self.danhsachphongtro_value.append(namephongtro)
                self.verticalLayout.addWidget(namephongtro)
    

    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", f"Phòng trọ {self.value}"))
        self.danhsachphongtro.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:26pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Danh sách phòng trọ</p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Themphongtro.setText(_translate("MainWindow", "Thêm phòng trọ"))
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
